const candidates = [
  {
    id: 1,
    name: "Sumit Ashok Gamre",
    gender: "Groom",
    dob: "14 Aug 1992",
    height: "5 ft 8 in",
    weight: "68 kg",
    education: "B.Tech Mechanical Eng.",
    salary: "8 LPA",
    currentLocation: "Titwala",
    villageLocation: "Ratnagiri",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "1.jpg",
    bio: "Active in social work, values family traditions and community pride.",
    mobile: "9221652441"
  },

  {
    id: 2,
    name: "Manisha Uttam Chavan",
    gender: "Bride",
    dob: "20 Mar 1993",
    height: "5 ft 5 in",
    weight: "70 kg",
    education: "B.A",
    salary: "2 LPA",
    currentLocation: "Titwala",
    villageLocation: "Beed",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "2.jpg",
    bio: "Expect non-addictive and educated",
    mobile: "8108871419"
  },

  {
    id: 3,
    name: "Goutam Govind Mande",
    gender: "Groom",
    dob: "09 Sep 1991",
    height: "5 ft 1 in",
    weight: "50 kg",
    education: "10",
    salary: "--",
    currentLocation: "Mankhurd, Mumbai",
    villageLocation: "Belapur",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "3.jpg",
    bio: "Good",
    mobile: "8779377017"
  },

  {
    id: 4,
    name: "Bhuvneshwari Vilas Nikunth",
    gender: "Bride",
    dob: "14 Apr 2001",
    height: "5 ft 7 in",
    weight: "70 kg",
    education: "M.Sc (Chemistry)",
    salary: "-",
    currentLocation: "Titwala",
    villageLocation: "Jalgaon",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "4.jpg",
    bio: "Expect simple, caring, and Govt or private job",
    mobile: "9867459286"
  },

  {
    id: 5,
    name: "Dilip Bapu Hinge",
    gender: "Groom",
    dob: "24 Mar 1988",
    height: "5 ft 5 in",
    weight: "65 kg",
    education: "6",
    salary: "2.4 LPA",
    currentLocation: "Vasind, Thane",
    villageLocation: "Latur",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "5.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "7057311225"
  },

  {
    id: 6,
    name: "Sandip Bhalerao",
    gender: "Groom",
    dob: "07 Nov 1998",
    height: "5 ft 5 in",
    weight: "45 kg",
    education: "12",
    salary: "1.5 LPA",
    currentLocation: "Khadawali, Thane",
    villageLocation: "Nashik, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "6.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9988776655"
  },

  {
    id: 7,
    name: "Kishor Rajiv More",
    gender: "Groom",
    dob: "05 Oct 1989",
    height: "5 ft 4 in",
    weight: "45 kg",
    education: "8",
    salary: "2.5 LPA",
    currentLocation: "Kasara, Thane",
    villageLocation: "Nashik, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "7.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9988776655"
  },

  {
    id: 8,
    name: "Sagar Pradip Bhalerao",
    gender: "Groom",
    dob: "20 Mar 1993",
    height: "5 ft 5 in",
    weight: "45 kg",
    education: "8",
    salary: "1.8 LPA",
    currentLocation: "Khadawali, Thane",
    villageLocation: "Nashik, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "8.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "7821805297"
  },

  {
    id: 9,
    name: "Abhijit Ashok Shirke",
    gender: "Groom",
    dob: "22 Nov 1995",
    height: "6 ft 0 in",
    weight: "72 kg",
    education: "Mechanical Eng.",
    salary: "3.5 LPA",
    currentLocation: "Mumbra, Thane",
    villageLocation: "Ratnagiri, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "9.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "7021312143"
  },

  {
    id: 10,
    name: "Shubham Anil Ubale",
    gender: "Groom",
    dob: "27 Jul 1998",
    height: "5 ft 6 in",
    weight: "58 kg",
    education: "Mechanical Eng.",
    salary: "4.5 LPA",
    currentLocation: "Titwala, Thane",
    villageLocation: "Igatpuri, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "10.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "7276673559"
  },

  {
    id: 11,
    name: "Lokesh Arjun Gaikwad",
    gender: "Groom",
    dob: "11 Apr 1988",
    height: "5 ft 8 in",
    weight: "58 kg",
    education: "12",
    salary: "10.20 LPA",
    currentLocation: "Ambernath, Thane",
    villageLocation: "Ambernath, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "11.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9767743775"
  },

  {
    id: 12,
    name: "Aakash Satrev Rajguru",
    gender: "Groom",
    dob: "16 Feb 1996",
    height: "5 ft 8 in",
    weight: "58 kg",
    education: "M.Com",
    salary: "6.0 LPA",
    currentLocation: "Ambivali, Thane",
    villageLocation: "Ambivali, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "12.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "8976534807"
  },

  {
    id: 13,
    name: "Sanjay Anil Bhatkar",
    gender: "Groom",
    dob: "04 Oct 1997",
    height: "5 ft 5 in",
    weight: "57 kg",
    education: "B.Com",
    salary: "3.5 LPA",
    currentLocation: "Titwala, Thane",
    villageLocation: "Amravati, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "13.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9082778592"
  },

  {
    id: 14,
    name: "Priti Kiran Shardul",
    gender: "Bride",
    dob: "24 Jun 1999",
    height: "5 ft 3 in",
    weight: "75 kg",
    education: "Master of Pharmacy",
    salary: "--",
    currentLocation: "Bhandup, Mumbai",
    villageLocation: "Nashik, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "14.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9819043231"
  },

  {
    id: 15,
    name: "Raman Prabhakar Kharat",
    gender: "Groom",
    dob: "02 Jul 1990",
    height: "5 ft 3 in",
    weight: "70 kg",
    education: "S.Y.B.A",
    salary: "4.2 LPA",
    currentLocation: "Titwala, Mumbai",
    villageLocation: "Chembur, Maharashtra",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "15.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9867973711"
  },
  {
    id: 16,
    name: "Ganesh Tukaram Padle",
    gender: "Groom",
    dob: "22 Jun 1989",
    height: "5 ft 3 in",
    weight: "80 kg",
    education: "T.Y.B.A",
    salary: "2.4 LPA",
    currentLocation: "Thane",
    villageLocation: "Thane",
    community: "Buddhist",
    maritalStatus: "Divorsed",
    image: "16.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9819458796"
  },
    {
    id: 17,
    name: "Amol Uttma Hire",
    gender: "Groom",
    dob: "08 Oct 1994",
    height: "5 ft 8 in",
    weight: "75 kg",
    education: "B.E Mechanical",
    salary: "2.4 LPA",
    currentLocation: "Titwala",
    villageLocation: "Titwala",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "17.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "9930819166"
  },
    {
    id: 18,
    name: "Yuvraj Tukaram Kanbale",
    gender: "Groom",
    dob: "12 Jun 1997",
    height: "4 ft 8 in",
    weight: "60 kg",
    education: "10",
    salary: "3.0 LPA",
    currentLocation: "Titwala",
    villageLocation: "Kolhapur",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "18.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "8010685575"
  },
    {
    id: 19,
    name: "Harshal Chandu Sangare",
    gender: "Groom",
    dob: "29 Sep 1997",
    height: "5 ft 6 in",
    weight: "60 kg",
    education: "B.E",
    salary: "--",
    currentLocation: "Bhiwandi",
    villageLocation: "Bhiwandi",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "19.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "776819010"
  }
  ,
    {
    id: 20,
    name: "Rohit Mangesh Gaikwad",
    gender: "Groom",
    dob: "25 Aug 2000",
    height: "5 ft 5 in",
    weight: "80 kg",
    education: "B.A LLB",
    salary: "1.2 LPA",
    currentLocation: "Titwala",
    villageLocation: "Titwala",
    community: "Buddhist",
    maritalStatus: "Never Married",
    image: "19.jpg",
    bio: "Family-oriented, believes in mutual respect and understanding.",
    mobile: "7506453797"
  }
];
